services:
#    platform.example:
#        class: Vin\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    platform.antispam:
        class: Vin\PlatformBundle\Antispam\VinAntispam